const Response = {
	DIRECTORY_NOT_LOADED: "DIRECTORY_NOT_LOADED",
	INVALID_PATH: "INVALID_PATH", 
	PATH_NOT_DIRECTORY: "PATH_NOT_DIRECTORY", 
	NOT_INITIALIZED: "NOT_INITIALIZED", 
	NO_SESSION: "NO_SESSION",
    PARAMETERS_NOT_FOUND: "PARAMETERS_NOT_FOUND", 
    PATH_DOESNT_EXIST: "PATH_DOESNT_EXIST"
}