package com.fileapp.utils;

public enum ResponseError {
    DIRECTORY_NOT_LOADED, INVALID_PATH, PATH_NOT_DIRECTORY, NOT_INITIALIZED, NO_SESSION,
    PARAMETERS_NOT_FOUND, PATH_DOESNT_EXIST, FILE_TOO_BIG
}